name: Automated Release on Tag Push

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:  # IMPORTANT - all of these are required
      id-token: write
      contents: write
      packages: write
    name: Automated Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3

      - name: Fetch secrets from Akeyless
        id: fetch-secrets
        uses: akeyless-community/akeyless-action@v3
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}     # (ex: 'p-iwt13fd19ajd') We recommend storing this as a GitHub Actions secret
          static-secrets: '{"/GitHub/token":"HOMEBREW_TAP_GITHUB_TOKEN"}'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          # distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.fetch-secrets.outputs.HOMEBREW_TAP_GITHUB_TOKEN }}